-- iMorphTools Data Tables
-- 数据已拆分到 data/ 目录下的各模块文件
-- 加载顺序由 iMorphTools.toc 控制：
--   data/core.lua       → IMT 命名空间 + BuildIDTable
--   data/commands.lua   → 便捷改模指令集
--   data/sets.lua       → 套装映射
--   data/models.lua     → 角色模型 + 宠物模型
--   data/mounts.lua     → 坐骑数据（经典+至暗+地心+巨龙+角斗士）
--   data/races.lua      → 种族
--   data/shapeshifts.lua→ 变形形态 + 形态模型
--   data/enchants.lua   → 武器附魔
--   data/spells.lua     → 技能效果
--   data/playkit.lua    → 视觉套件 + 装备栏位
